#pragma once
//Automatically generated build count file. DO NOT EDIT MANUALLY!

#define BUILD_COUNT_ANUBIS 118
#define BUILD_COUNT_BLAZAR 56
#define BUILD_COUNT_BOYC_PC 146
#define BUILD_COUNT_CONSPIRATOR 13778
#define BUILD_COUNT_DESKTOP_2129QAG 13
#define BUILD_COUNT_DESKTOP_EDTCHAL 5771
#define BUILD_COUNT_DESKTOP_P2HGH2D 157

#define RELEASE_COUNT_ANUBIS 0
#define RELEASE_COUNT_BLAZAR 1
#define RELEASE_COUNT_BOYC_PC 0
#define RELEASE_COUNT_CONSPIRATOR 337
#define RELEASE_COUNT_DESKTOP_2129QAG 0
#define RELEASE_COUNT_DESKTOP_EDTCHAL 156
#define RELEASE_COUNT_DESKTOP_P2HGH2D 6

#define BUILDCOUNT (BUILD_COUNT_ANUBIS+BUILD_COUNT_BLAZAR+BUILD_COUNT_BOYC_PC+BUILD_COUNT_CONSPIRATOR+BUILD_COUNT_DESKTOP_2129QAG+BUILD_COUNT_DESKTOP_EDTCHAL+BUILD_COUNT_DESKTOP_P2HGH2D)
#define RELEASECOUNT (RELEASE_COUNT_ANUBIS+RELEASE_COUNT_BLAZAR+RELEASE_COUNT_BOYC_PC+RELEASE_COUNT_CONSPIRATOR+RELEASE_COUNT_DESKTOP_2129QAG+RELEASE_COUNT_DESKTOP_EDTCHAL+RELEASE_COUNT_DESKTOP_P2HGH2D)
