#pragma once

// configure these based on code coverage for the current prod
// if you add any new macros here, add them as enabled to the
// default phoenixconfig.h

#define PHX_SPLINE_WAVEFORM_SUPPORT

#define PHX_ARBARO_HAVE_HELIX_SUPPORT
#define PHX_ARBARO_HAVE_PRUNING
#define PHX_ARBARO_HAVE_FAN_LEAVES
#define PHX_ARBARO_HAVE_NEGATIVE_TRUNK_ROTANGLE

#define PHX_ARBARO_HAS_SHAPE_CONICAL
#define PHX_ARBARO_HAS_SHAPE_SPHERICAL
#define PHX_ARBARO_HAS_SHAPE_HEMISPHERICAL
#define PHX_ARBARO_HAS_SHAPE_CYLINDRICAL
#define PHX_ARBARO_HAS_SHAPE_TAPERED_CYLINDRICAL
#define PHX_ARBARO_HAS_SHAPE_FLAME
#define PHX_ARBARO_HAS_SHAPE_INVERSE_CONICAL
#define PHX_ARBARO_HAS_SHAPE_TEND_FLAME

#define PHX_SCATTER_HAS_VERTEX_SUPPORT
#define PHX_SCATTER_HAS_EDGE_SUPPORT
#define PHX_SCATTER_HAS_POLY_SUPPORT
#define PHX_SCATTER_HAS_POLY_MORE_THAN_1_INSTANCE_SUPPORT

#define PHX_QUATERNION_HAS_QUADRATIC
#define PHX_HAS_NON_DEMO_RELATIVE_RENDERTARGETS
#define PHX_HAS_SCENE_OBJECT_HIERARCHIES

#define PHX_VOLUMETRIC_RENDERTARGETS